FROM ubuntu:22.04

# Install necessary packages
RUN apt-get update && apt-get install -y python3 python3-pip nginx
RUN apt-get update && apt-get install -y python3  python3-pip 
# Set the working directory in the container
WORKDIR /app

# Copy the Django application code to the container
COPY . .

# convert all shell script to executable
RUN chmod +x *.sh

# Build wheel packages
RUN pip install -r requirements.txt

EXPOSE 1337

CMD ["/app/worker-entrypoint.sh"]