version: '3.9'

services:
  db:
    image: postgres:16.0
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: redis_server
    expose:
      - 6379
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
