services:
  backend:
    build:
      dockerfile: Dockerfile
    container_name: backend
    entrypoint: [ "./entrypoint.sh" ]
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    environment:
      - REDIS_URL=${REDIS_URL_PROD}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL_PROD}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND_PROD}
      - DATABASE_USER=${DATABASE_USER_PROD}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD_PROD}
      - DATABASE_HOST=${DATABASE_HOST_PROD}
      - DEBUG=${DEBUG_PROD}
    depends_on:
      - db
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8000/health-check"
        ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  nginx:
    build:
      dockerfile: Dockerfile.nginx
    container_name: nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - .:/home/app/web
    ports:
      - "1337:80"
    depends_on:
      - backend

  db:
    image: postgres:16.0
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

    environment:
      - POSTGRES_ROOT_PASSWORD=${POSTGRES_ROOT_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  redis:
    image: redis:alpine
    container_name: redis
    expose:
      - 6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  celery:
    build:
      dockerfile: Dockerfile # I think we should create a separate Dockerfile for celery
    container_name: celery
    entrypoint: [ "./worker-entrypoint.sh" ]
    volumes:
      - celery_volume:/home/app/web/celeryfiles
      - .:/home/app/web
    environment:
      - REDIS_URL=${REDIS_URL_PROD}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL_PROD}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND_PROD}
    depends_on:
      - db
      - redis

volumes:
  static_volume:
  media_volume:
  postgres_data:
  celery_volume:
