version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    entrypoint: [ "./entrypoint.sh" ]
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - "1337:80"
    depends_on:
      - backend

  db:
    image: postgres:16.0
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

  redis:
    image: redis:alpine
    container_name: redis_server
    expose:
      - 6379

  celery:
    build:
      context: .
      dockerfile: Dockerfile # I think we should create a separate Dockerfile for celery
    container_name: celery
    entrypoint: [ "./worker-entrypoint.sh" ]
    volumes:
      - celery_volume:/home/app/web/celeryfiles
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

volumes:
  static_volume:
  media_volume:
  postgres_data:
  celery_volume:
