# Generated by Django 5.0.6 on 2024-07-31 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('soil_moisture', 'Soil Moisture'), ('co2', 'CO2'), ('light', 'Light')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['sensor_type', 'timestamp'], name='sensor_sens_sensor__eb8942_idx')],
            },
        ),
        migrations.CreateModel(
            name='LightSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('temp & humidity', 'Temperature & Humidity'), ('soil_moisture', 'Soil Moisture'), ('co2', 'CO2'), ('light', 'Light')], max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('unit', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=50)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='light_sensor', to='farm.room')),
                ('light_level', models.ManyToManyField(blank=True, related_name='light_data', to='sensor.sensordata')),
            ],
            options={
                'ordering': ['-last_updated'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CO2Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('temp & humidity', 'Temperature & Humidity'), ('soil_moisture', 'Soil Moisture'), ('co2', 'CO2'), ('light', 'Light')], max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('unit', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=50)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co2_sensor', to='farm.room')),
                ('co2_level', models.ManyToManyField(blank=True, related_name='co2_data', to='sensor.sensordata')),
            ],
            options={
                'ordering': ['-last_updated'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoilMoistureSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('temp & humidity', 'Temperature & Humidity'), ('soil_moisture', 'Soil Moisture'), ('co2', 'CO2'), ('light', 'Light')], max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('unit', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=50)),
                ('moisture_level', models.ManyToManyField(blank=True, related_name='moisture_data', to='sensor.sensordata')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_moisture_sensor', to='farm.room')),
            ],
            options={
                'ordering': ['-last_updated'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemperatureHumiditySensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('temp & humidity', 'Temperature & Humidity'), ('soil_moisture', 'Soil Moisture'), ('co2', 'CO2'), ('light', 'Light')], max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('unit', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=50)),
                ('humidity', models.ManyToManyField(blank=True, related_name='humidity_data', to='sensor.sensordata')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_humidity_sensor', to='farm.room')),
                ('temperature', models.ManyToManyField(blank=True, related_name='temperature_data', to='sensor.sensordata')),
            ],
            options={
                'ordering': ['-last_updated'],
                'abstract': False,
            },
        ),
    ]
