# Generated by Django 5.0.6 on 2024-06-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CO2Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('temp & humidity', 'Temperature & Humidity'), ('soil_moisture', 'Soil Moisture'), ('co2', 'CO2'), ('light', 'Light')], max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('unit', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=50)),
                ('co2_level', models.FloatField()),
            ],
            options={
                'ordering': ['-last_updated'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LightSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('temp & humidity', 'Temperature & Humidity'), ('soil_moisture', 'Soil Moisture'), ('co2', 'CO2'), ('light', 'Light')], max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('unit', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=50)),
                ('light_level', models.FloatField()),
            ],
            options={
                'ordering': ['-last_updated'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoilMoistureSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('temp & humidity', 'Temperature & Humidity'), ('soil_moisture', 'Soil Moisture'), ('co2', 'CO2'), ('light', 'Light')], max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('unit', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=50)),
                ('moisture_level', models.FloatField()),
            ],
            options={
                'ordering': ['-last_updated'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemperatureHumiditySensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('temp & humidity', 'Temperature & Humidity'), ('soil_moisture', 'Soil Moisture'), ('co2', 'CO2'), ('light', 'Light')], max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('unit', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=50)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
            ],
            options={
                'ordering': ['-last_updated'],
                'abstract': False,
            },
        ),
    ]
