# Generated by Django 5.0.6 on 2024-07-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='co2sensor',
            name='co2_level',
        ),
        migrations.RemoveField(
            model_name='lightsensor',
            name='light_level',
        ),
        migrations.RemoveField(
            model_name='soilmoisturesensor',
            name='moisture_level',
        ),
        migrations.AddField(
            model_name='co2sensor',
            name='co2_level',
            field=models.ManyToManyField(blank=True, related_name='co2_data', to='sensor.sensordata'),
        ),
        migrations.AddField(
            model_name='lightsensor',
            name='light_level',
            field=models.ManyToManyField(blank=True, related_name='light_data', to='sensor.sensordata'),
        ),
        migrations.AddField(
            model_name='soilmoisturesensor',
            name='moisture_level',
            field=models.ManyToManyField(blank=True, related_name='moisture_data', to='sensor.sensordata'),
        ),
    ]
