# Generated by Django 5.0.6 on 2024-06-20 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushroom', '0001_initial'),
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='co2sensor',
            name='microcontroller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mushroom.microcontroller'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lightsensor',
            name='microcontroller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mushroom.microcontroller'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soilmoisturesensor',
            name='microcontroller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mushroom.microcontroller'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperaturehumiditysensor',
            name='microcontroller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mushroom.microcontroller'),
            preserve_default=False,
        ),
    ]
