# Generated by Django 5.0.6 on 2024-07-26 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='rooms',
        ),
        migrations.AddField(
            model_name='room',
            name='farm',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='farm.farm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=9, max_digits=13),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=9, max_digits=13),
        ),
    ]
